### ISSUE TITLE
Literal converted to type from Literal value

### ISSUE THREAD

**Issue by Malachov** [microsoft/pylance-release#2094]
```python
def f(a: Literal[1, 2, 3]) -> Literal[1, 2, 3]:
    return a

b = f(2)
b  # intellisense shows int instead of Literal[1, 2, 3]
```
![image](https://user-images.githubusercontent.com/39381691/142773758-95c8ef59-ad0c-4c5a-aa48-1cccf01dd8bb.png)

If i try this on mypy [playgound](url) and add 

`print(reveal_type(b))`

It returns `Literal[1, 2, 3]`

This may not be a bug but my misunderstanding though...

TLDR:
This is just minified version of where i have the problem, but i think this is the root of it.

Main part of my problem is

```python
def type_hinted_result(f: Callable[[], U]) -> U:
    return f()
```

This convert
`Literal[1, 2, 3]` to int 
`Literal["one, "two"]` to str

**Comment by erictraut** [comment]
I'm not able to reproduce the problem with your simplified example. Intellisense displays the type of `b` as `Literal[1, 2, 3]` as you expect. 

![Screen Shot 2021-11-21 at 10 30 03 AM](https://user-images.githubusercontent.com/7040122/142774485-e90da719-0cf8-4160-9c21-c5439bf9bc23.png)
 
Can you verify that you're able to repro it with the simplified example?

For your second example, I can't tell what `U` is. Is it a TypeVar? A type alias? I'd need a more complete example to diagnose that one.

**Comment by Malachov** [comment]
If i do mouseover, it's correct Literal in tooltip, when i use autocomplete (ctrl + spacebar), it's `int` but it's maybe because of what functions can be applied to that variable. Anyway in second example it's TypeVar and wrong type is passed further. I use it to create a configuration module - that use something similar to property with predefined setters. 
I use descriptors with editing `__set__` method.

I want to write configuration like:
```python
class Config:
    @myproperty
    def my_config_value() -> Literal[1, 2, 3]:
        """Here the docs"""
        return self.another_vaue + 1
```

Now i want the user so if he does

```python
config = Config()
config.my_config_value = 5  # IDE shouts here

How it works for me now...?

![image](https://user-images.githubusercontent.com/39381691/142781727-1bfe1999-2050-4c37-bd1a-35b780817a61.png)

I tried to use class decorator, but i didn't make TypeVar from init to work in __set__

Type hints around descriptor are kind of made, but not documented much and may not even been finalized.

I made workaround with using normal function decorator that return Generic descriptor.
It works if I define type in decorating function return.

Problem is, that return type of `fget` in method is not passed on output in function wrapper,

There is a [link](https://github.com/Malachov/mypythontools/blob/master/mypythontools/property.py) for current solution where `Literal["one, "two"]` is converted to str

I tried
- ParamSpec

Alternatives i tried before this solution of generic descriptor - Using just normal property where it works and define shared setter
- defined in metaclass
- defined in __init__ via ___class__

None of that worked.

Thank you very much for help. If change from Literal to type of values is not because of pyright, close that issue (if you have some tip what to try, appreciated... :) i know that Callable protocols may help).

I also don't know whether its even possible.

Btw: I use python 3.9, but it's the same with 3.7 and 3.10
Pylance:  v2021.11.2  (not sure of what pyright version it uses)

**Comment by erictraut** [comment]
The TypeVar constraint solver includes many heuristics that dictate whether (and under what circumstances) a literal type should be captured or the wider type associated with a literal type. Heuristics are required here because PEP 484 and 586 do not provide specific. And in fact, PEP 586 intentionally leaves it up to individual type checkers to decide how to deal with this case. For pyright (the type checker upon which pylance is built), these heuristics have been tuned based on many bug reports over the years. In this particular example, the type variable is being widened, effectively stripping the literal. Mypy (another popular Python type checker) does the same in this case.

One potential solution is to abandon the MyProperty wrapper function and use the class directly. For generic classes (unlike generic functions), you are able to directly specify the intended specialization, overriding any heuristics in the TypeVar constraint solver. You could fall back on the normal heuristics in cases other than literals.

Here's what that would look like:

```python
    @MyPropertyClass[Literal["asd", "rbrb"]]
    def var_literal(self) -> Literal["asd", "rbrb"]:
        return "asd"
```

With this approach, both pyright and mypy generate the type errors you were expecting to see.

The downside to this approach is that it relies on the functionality introduced in PEP 614, so it doesn't work with versions of Python prior to 3.9. I don't know if that's a problem for your use case.

**Comment by Malachov** [comment]
PEP 614 is cool solution for me. I will wait with feature till python older than 3.9 is depracated.

Though still i don't understand why Literal type in TypeVar is widened when Literal is defined in function type hints and is not inferred via type checker.

Here is minimal working code:

```python
from __future__ import annotations
from typing import Generic, TypeVar, Callable, Literal


T = TypeVar("T")


class MyPropertyClass(Generic[T]):
    """Python property on steroids. Check module docstrings for more info."""

    def __init__(self, fget: Callable[..., T] = None):
        pass

    def __set__(self, object, content: T | Callable[..., T]):
        # Some logic here
        pass


def MyProperty(f: Callable[..., T]) -> MyPropertyClass[T]:
    return MyPropertyClass[T](f)


class Example:
    @MyProperty
    def var_literal(self) -> Literal["OK1", "OK2"]:  # Literal options are also validated
        return "OK1"


example = Example()

example.var_literal = "OK1"  # Correct
example.var_literal = "Not OK"  # This should not work, but Pyright says OK because Literal was widened
```
On MyPY it is correctly declined with valid error

`main.py:32: error: Incompatible types in assignment (expression has type "Literal['Not OK']", variable has type "Union[Literal['OK1'], Literal['OK2'], Callable[..., Union[Literal['OK1'], Literal['OK2']]]]")`

In pyright it's widened to str, so Pylance validate it as OK...

IMHO TypeVar from Callable return shouldn't be widened in this situation when Literal defined in Type hints, but i understand, that there are many use cases and it's not easy maybe not even possible to suit all the use cases and i can imagine that not widening similar case can cause troubles. Heuristic is the only way yet as also python type hints are still quite fresh. 

Thank you very much for help and awesome tools... **Feel free to close the issue** if there is reason for this behavior or it's to complicated to implement...
